blank_issues_enabled: false
contact_links:
  - name: Feature request
    url: https://github.com/ptr727/homeassistant-purpleair/discussions/new?category=ideas
    about: Suggest a new feature or improvement.
  - name: Question or help
    url: https://github.com/ptr727/homeassistant-purpleair/discussions/new?category=q-a
    about: Ask a question or get help using the integration.
